# Generated by Django 6.0.3 on 2026-03-06 15:55

import apps.stores.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('whatsapp_number', models.CharField(max_length=20)),
                ('logo', models.ImageField(blank=True, upload_to=apps.stores.models.store_logo_path)),
                ('primary_color', models.CharField(default='#000000', max_length=7)),
                ('hero_title', models.CharField(blank=True, max_length=255)),
                ('hero_subtitle', models.CharField(blank=True, max_length=255)),
                ('cta_text', models.CharField(default='Ver catálogo', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
